/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateGameDto {
    'blueTeamId': number;
    'redTeamId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blueTeamId",
            "baseName": "blueTeamId",
            "type": "number"
        },
        {
            "name": "redTeamId",
            "baseName": "redTeamId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateGameDto.attributeTypeMap;
    }
}

