/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventStatus } from './eventStatus';

export class CreateEventDto {
    'name': string;
    /**
    * Describe the event!
    */
    'description'?: string;
    'startDate': Date;
    'endDate': Date;
    /**
    * The intended starting status of the event.
    */
    'status': EventStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EventStatus"
        }    ];

    static getAttributeTypeMap() {
        return CreateEventDto.attributeTypeMap;
    }
}

export namespace CreateEventDto {
}
