/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EventCreateSeriesDto {
    'team1Id': number;
    'team2Id': number;
    'totalGames': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "team1Id",
            "baseName": "team1Id",
            "type": "number"
        },
        {
            "name": "team2Id",
            "baseName": "team2Id",
            "type": "number"
        },
        {
            "name": "totalGames",
            "baseName": "totalGames",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return EventCreateSeriesDto.attributeTypeMap;
    }
}

