/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EventStatus } from './eventStatus';
import { TeamDto } from './teamDto';

export class EventWithTeamsDto {
    'id': number;
    'name': string;
    'description': string;
    'createdAt': Date;
    'startDate': Date;
    'endDate': Date;
    /**
    * The current event status.
    */
    'status': EventStatus;
    'eventGroupId': number | null;
    'teams': Array<TeamDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EventStatus"
        },
        {
            "name": "eventGroupId",
            "baseName": "eventGroupId",
            "type": "number"
        },
        {
            "name": "teams",
            "baseName": "teams",
            "type": "Array<TeamDto>"
        }    ];

    static getAttributeTypeMap() {
        return EventWithTeamsDto.attributeTypeMap;
    }
}

export namespace EventWithTeamsDto {
}
