/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GameDto {
    'id': number;
    'shortcode': string;
    'blueTeamId': number;
    'redTeamId': number;
    'seriesId': number;
    'number': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "shortcode",
            "baseName": "shortcode",
            "type": "string"
        },
        {
            "name": "blueTeamId",
            "baseName": "blueTeamId",
            "type": "number"
        },
        {
            "name": "redTeamId",
            "baseName": "redTeamId",
            "type": "number"
        },
        {
            "name": "seriesId",
            "baseName": "seriesId",
            "type": "number"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GameDto.attributeTypeMap;
    }
}

