/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RiotAccountDto } from './riotAccountDto';

export class PlayerDto {
    'id': number;
    'name': string;
    'accounts'?: Array<RiotAccountDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<RiotAccountDto>"
        }    ];

    static getAttributeTypeMap() {
        return PlayerDto.attributeTypeMap;
    }
}

