/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RiotAccountDto {
    'id': number;
    /**
    * Riot\'s permanent unique user ID (78 chars)
    */
    'riotPuuid': string;
    'playerId'?: number | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "riotPuuid",
            "baseName": "riotPuuid",
            "type": "string"
        },
        {
            "name": "playerId",
            "baseName": "playerId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RiotAccountDto.attributeTypeMap;
    }
}

