/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TeamDto } from './teamDto';

export class SeriesDto {
    'id': number;
    'eventId': number;
    'teams': Array<TeamDto>;
    'totalGames': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "number"
        },
        {
            "name": "teams",
            "baseName": "teams",
            "type": "Array<TeamDto>"
        },
        {
            "name": "totalGames",
            "baseName": "totalGames",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SeriesDto.attributeTypeMap;
    }
}

