/**
 * Dennys - OpenAPI 3.0
 * This is the Dennys OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: lblcs.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PlayerDto } from './playerDto';

export class TeamWithPlayersDto {
    'id': number;
    'name': string;
    'logoName'?: string | null;
    'eventId'?: number | null;
    'players': Array<PlayerDto>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "logoName",
            "baseName": "logoName",
            "type": "string"
        },
        {
            "name": "eventId",
            "baseName": "eventId",
            "type": "number"
        },
        {
            "name": "players",
            "baseName": "players",
            "type": "Array<PlayerDto>"
        }    ];

    static getAttributeTypeMap() {
        return TeamWithPlayersDto.attributeTypeMap;
    }
}

