name: Extract project version
outputs:
  version: 
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - name: Extract version number
      id: version
      shell: bash
      run: |
        VERSION=$(cat version.json | jq '.version')
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

