on:
  push:
    branches:
      - main
      - release/*

jobs:
  set-version:
    name: Extracts app version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract app version
        id: setup
        uses: ./.github/actions/extract-version
    outputs:
      version: ${{ steps.setup.outputs.version }}

  build-artifact:
    name: Build, compress, and upload distribution 
    runs-on: ubuntu-latest
    needs: 
      - set-version 
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies 
        run: npm i

      - name: Calculate build-time variables
        run: |
          if [[ ${GITHUB_REF} == 'main' ]]; then
            declare dennys_url="https://dennys.lowbudgetlcs.com"
          else
            declare    version=${{ needs.set-version.outputs.version }}
            declare    plain_version="${version/\.//}"
            declare    dennys_url="https://dennys-${plain_version}.lowbudgetlcs.com"
          fi
          echo "VITE_DENNYS_API_URL=${dennys_url}" >> .env

      - name: Build distro 
        run: npm run build
      
      - name: Compress distro
        run: tar -czvf dist.tgz dist

      - name: Upload distro 
        uses: actions/upload-artifact@v6
        with:
          name: distro
          path: dist.tgz

  deploy-artifact:
    name: Deploys the build to production
    runs-on: ubuntu-latest
    needs:
      - set-version
      - build-artifact
    steps:
      - name: Download distro 
        uses: actions/download-artifact@v6
        with:
          name: distro 
          path: distfiles
 
      - name: Configure variables
        run: |
          if [[ ${GITHUB_REF} == 'main' ]]; then
            echo "directory=/releases/stephen/latest" >> "$GITHUB_ENV"
          else
            declare    version=${{ needs.set-version.outputs.version }}
            echo "directory=/releases/stephen/${version}" >> "$GITHUB_ENV"
          fi

      - name: Downlod distro via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST}}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: distfiles/*
          target: "${{ env.directory }}"
          strip_component: 1

      - name: Extract dist into dist/ dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd "${{ env.directory }}"
            tar -xzvf dist.tgz -C dist 




